In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [3]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [6]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [7]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [8]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [9]:
max_views = np.max(views)
max_views

np.int64(1200)

In [10]:
min_views = np.min(views)
min_views

np.int64(300)

In [12]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(733.33)

In [13]:
total_views = np.sum(views)
total_views

np.int64(4400)