In [2]:
import numpy as np

In [3]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
np.zeros((3, 4), dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
np.ones((5, 3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
np.random.random((2, 4))

array([[0.71201335, 0.8076185 , 0.0670717 , 0.63077775],
       [0.80909748, 0.46926983, 0.51036952, 0.246588  ]])