In [1]:
import numpy as np

In [2]:
first = np.array([[1, 2, 3], [4, 5, 6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
first.shape

(2, 3)

In [4]:
first.ndim

2

In [5]:
second = np.array([[7, 8, 9], [10, 11, 12]])
second

array([[ 7,  8,  9],
       [10, 11, 12]])

In [6]:
second.shape

(2, 3)

In [7]:
first + second

array([[ 8, 10, 12],
       [14, 16, 18]])

In [8]:
first + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [10]:
first - 2

array([[-1,  0,  1],
       [ 2,  3,  4]])

In [11]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [12]:
first / 3

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [13]:
first

array([[1, 2, 3],
       [4, 5, 6]])