In [1]:
import numpy as np

## 1. Calculating Total Revenue

In [2]:
prices = np.array([19.99, 29.99, 14.99, 9.99, 24.99])
prices

array([19.99, 29.99, 14.99,  9.99, 24.99])

In [3]:
quantities = np.array([10, 5, 8, 12, 3])
quantities

array([10,  5,  8, 12,  3])

In [6]:
revenue_per_product = prices * quantities
revenue_per_product

array([199.9 , 149.95, 119.92, 119.88,  74.97])

In [7]:
total_revenue = np.sum(revenue_per_product)
total_revenue

np.float64(664.62)

## 2. Analyzing Blog Post Stats

In [8]:
views = np.array([1000, 500, 800, 1200, 300, 600])
views

array([1000,  500,  800, 1200,  300,  600])

In [9]:
max_views = np.max(views)
max_views

np.int64(1200)

In [10]:
min_views = np.min(views)
min_views

np.int64(300)

In [12]:
average_views = np.round(np.mean(views), 2)
average_views

np.float64(733.33)

In [13]:
total_views = np.sum(views)
total_views

np.int64(4400)

## 3. Splitting Order into Batches

In [17]:
order_ids = np.array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])
order_ids

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [18]:
batches = np.split(order_ids, 4)
batches

[array([1001, 1002]),
 array([1003, 1004]),
 array([1005, 1006]),
 array([1007, 1008])]

In [22]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}:")
    print("First element in the batch: ", batch[0])
    print("Second element in the batch: ", batch[1])
    print('')

Batch number 0:
First element in the batch:  1001
Second element in the batch:  1002

Batch number 1:
First element in the batch:  1003
Second element in the batch:  1004

Batch number 2:
First element in the batch:  1005
Second element in the batch:  1006

Batch number 3:
First element in the batch:  1007
Second element in the batch:  1008



## 4. Categorizing Product Ratings

In [23]:
ratings = np.array([4.5, 3.2, 2.8, 5.0, 4.1, 3.9, 2.5, 4.7])
ratings

array([4.5, 3.2, 2.8, 5. , 4.1, 3.9, 2.5, 4.7])

In [24]:
positive_ratings = ratings[ratings >= 4.0]
positive_ratings

array([4.5, 5. , 4.1, 4.7])

In [26]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([3.2, 2.8, 3.9, 2.5])

## 5. Calculate Total and Average quantities sold

In [30]:
# Each column is specific product (we have 4 products)
# Each row is specific order( we have 2 orders)
order_quantities = np.array([[5, 3, 2, 7], [10, 6, 3, 9]])
order_quantities

array([[ 5,  3,  2,  7],
       [10,  6,  3,  9]])

In [31]:
# Quantities of the sales per product
total_quantities_sold = np.sum(order_quantities, axis=0)
total_quantities_sold

array([15,  9,  5, 16])

In [33]:
# Quantities of the sales per order
total_products_per_order = np.sum(order_quantities, axis=1)
total_products_per_order

array([17, 28])

In [34]:
# Average quantities per product across all orders
average_quantities_sold = np.mean(order_quantities, axis=0)
average_quantities_sold

array([7.5, 4.5, 2.5, 8. ])

## Calculate Average product Rating and Maximum rating per Category

In [35]:
# Each row is one product
# Each product is rated in 4 categories
product_ratings = np.array([
    [4.5, 3.2, 2.5, 5.0],
    [4.3, 3.8, 1.0, 4.8],
    [2.0, 3.6, 4.7, 0.5]
])
product_ratings

array([[4.5, 3.2, 2.5, 5. ],
       [4.3, 3.8, 1. , 4.8],
       [2. , 3.6, 4.7, 0.5]])

In [37]:
# Avearge rating in each category
average_rating_per_category = np.mean(product_ratings, axis=0)
average_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])

In [38]:
# Avearge rating for each product
average_rating_per_product = np.mean(product_ratings, axis=1)
average_rating_per_product

array([3.8  , 3.475, 2.7  ])

In [37]:
# Maximum rating in each category
max_rating_per_category = np.max(product_ratings, axis=0)
max_rating_per_category

array([3.6       , 3.53333333, 2.73333333, 3.43333333])